// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThAmCo.Events.Data;

#nullable disable

namespace ThAmCo.Events.Data.Migrations
{
    [DbContext(typeof(EventsContext))]
    [Migration("20231213004905_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.23");

            modelBuilder.Entity("ThAmCo.Events.Data.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reference")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            BookingId = 47531,
                            DateAndTime = new DateTime(2023, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            MenuId = 0,
                            Name = "Event 1",
                            Reference = 59310
                        },
                        new
                        {
                            EventId = 2,
                            BookingId = 35105,
                            DateAndTime = new DateTime(2023, 1, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            MenuId = 0,
                            Name = "Event 2",
                            Reference = 93821
                        },
                        new
                        {
                            EventId = 3,
                            BookingId = 62318,
                            DateAndTime = new DateTime(2023, 9, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MenuId = 0,
                            Name = "Event 3",
                            Reference = 21523
                        });
                });

            modelBuilder.Entity("ThAmCo.Events.Data.EventGuest", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "GuestId");

                    b.HasIndex("GuestId");

                    b.ToTable("EventGuest");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            GuestId = 1
                        },
                        new
                        {
                            EventId = 1,
                            GuestId = 2
                        },
                        new
                        {
                            EventId = 2,
                            GuestId = 3
                        },
                        new
                        {
                            EventId = 2,
                            GuestId = 4
                        },
                        new
                        {
                            EventId = 3,
                            GuestId = 5
                        },
                        new
                        {
                            EventId = 3,
                            GuestId = 6
                        });
                });

            modelBuilder.Entity("ThAmCo.Events.Data.EventStaff", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("EventStaff");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            StaffId = 1
                        },
                        new
                        {
                            EventId = 1,
                            StaffId = 2
                        },
                        new
                        {
                            EventId = 2,
                            StaffId = 3
                        },
                        new
                        {
                            EventId = 2,
                            StaffId = 4
                        },
                        new
                        {
                            EventId = 3,
                            StaffId = 5
                        },
                        new
                        {
                            EventId = 3,
                            StaffId = 6
                        });
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuestId");

                    b.ToTable("Guest");

                    b.HasData(
                        new
                        {
                            GuestId = 1,
                            FirstName = "Samuel",
                            LastName = "Emmerson"
                        },
                        new
                        {
                            GuestId = 2,
                            FirstName = "Tony",
                            LastName = "Flanigan"
                        },
                        new
                        {
                            GuestId = 3,
                            FirstName = "Jonathon",
                            LastName = "Bartwick"
                        },
                        new
                        {
                            GuestId = 4,
                            FirstName = "Benjamin",
                            LastName = "Greenaway"
                        },
                        new
                        {
                            GuestId = 5,
                            FirstName = "Stephen",
                            LastName = "Bainbridge"
                        },
                        new
                        {
                            GuestId = 6,
                            FirstName = "Matthew",
                            LastName = "Bunny"
                        });
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            FirstName = "Josh",
                            LastName = "Parkinson"
                        },
                        new
                        {
                            StaffId = 2,
                            FirstName = "James",
                            LastName = "Swales"
                        },
                        new
                        {
                            StaffId = 3,
                            FirstName = "Lee",
                            LastName = "Harrison"
                        },
                        new
                        {
                            StaffId = 4,
                            FirstName = "Thomas",
                            LastName = "Hadfield"
                        },
                        new
                        {
                            StaffId = 5,
                            FirstName = "Greg",
                            LastName = "Tomlinson"
                        },
                        new
                        {
                            StaffId = 6,
                            FirstName = "Billy",
                            LastName = "Blackburn"
                        });
                });

            modelBuilder.Entity("ThAmCo.Events.Data.EventGuest", b =>
                {
                    b.HasOne("ThAmCo.Events.Data.Event", "Event")
                        .WithMany("Guests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Events.Data.Guest", "Guest")
                        .WithMany("Events")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("ThAmCo.Events.Data.EventStaff", b =>
                {
                    b.HasOne("ThAmCo.Events.Data.Event", "Event")
                        .WithMany("Staffs")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Events.Data.Staff", "Staff")
                        .WithMany("Events")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Event", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Guest", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Staff", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
